name: "AI Docs Sync (Codex Full Auto)"
description: "Autonomously updates documentation repo based on source repo diff"

inputs:
  base_sha:
    description: "Base commit SHA"
    required: true
  head_sha:
    description: "Head commit SHA"
    required: true
  openai_api_key:
    description: "OpenAI API Key"
    required: true
  docs_repo_token:
    description: "Token with write access to docs repo"
    required: true
  docs_repo:
    description: "Docs repo in owner/name format (e.g. Corgea/docs)"
    default: "Corgea/docs"
    required: false
  docs_base_branch:
    description: "Base branch in docs repo"
    required: false
    default: "main"

runs:
  using: "composite"
  steps:

    ##########################################################################
    # 1️⃣ Checkout SOURCE repo into /source
    ##########################################################################
    - name: Checkout source repository
      uses: actions/checkout@v5
      with:
        path: source

    ##########################################################################
    # 2️⃣ Generate diff file
    ##########################################################################
    - name: Generate diff
      shell: bash
      run: |
        cd source
        git fetch origin ${{ inputs.base_sha }}
        git fetch origin ${{ inputs.head_sha }}
        git diff ${{ inputs.base_sha }} ${{ inputs.head_sha }} > ./diff.txt
        cd ..
        
    - name: Print diff
      shell: bash
      run: |
        echo "===== Generated Diff ====="
        cat ./source/diff.txt
        echo "=========================="
        
    ##########################################################################
    # 3️⃣ Clone docs repo into /docs
    ##########################################################################
    - name: Clone docs repository
      shell: bash
      run: |
        git clone https://x-access-token:${{ inputs.docs_repo_token }}@github.com/${{ inputs.docs_repo }} docs
        cd docs
        git config user.name "docs-bot"
        git config user.email "docs-bot@users.noreply.github.com"

    ##########################################################################
    # 4️⃣ Run Codex using official GitHub Action
    ##########################################################################
    - name: Run Codex (full-auto)
      id: run_codex
      uses: openai/codex-action@v1
      with:
        openai-api-key: ${{ inputs.openai_api_key }}
        working-directory: .
        prompt: |
          You maintain our documentation repository.
    
          CONTEXT:
          - Source repository is located at ./source
          - Diff file is located at ./source/diff.txt
          - Docs repository is located at ./docs
          - We use Mintlify
          - Inspect mint.json to determine active documentation files
          - This is client-facing docs; it shouldn't include internal code snippets or describe internal algorithms
    
          YOUR TASK:
          1. Inspect ./source/diff.txt
          2. Inspect relevant parts of ./source/ if needed
          3. Inspect existing documentation located at ./docs
          4. Update, add, or remove ONLY documentation related to the diff
          5. After making changes, create a file ./pr.json with a concise PR title and description summarizing the documentation changes
    
          RULES:
          - DO NOT update changelogs
          - For API changes only modify OpenAPI reference docs
          - DO NOT refactor unrelated outdated sections
          - DO NOT perform large rewrites
          - Make minimal targeted edits
          - Only modify files referenced in mint.json
          - If no documentation updates are required, make NO changes and DO NOT create pr.json
          
          PR JSON FORMAT:
          Create ./pr.json with this structure:
          {
            "title": "Brief PR title describing the doc changes",
            "description": "1-3 sentence summary of what was updated in the docs and why"
          }
        sandbox: workspace-write

    ##########################################################################
    # 5️⃣ Create PR only if changes exist
    ##########################################################################
    - name: Create Pull Request if docs changed
      shell: bash
      run: |
        cd docs
        if [[ -z $(git status --porcelain) ]]; then
          echo "No documentation changes detected."
          exit 0
        fi

        # Read PR metadata from Codex-generated file
        if [[ -f ../pr.json ]]; then
          PR_TITLE=$(jq -r '.title' ../pr.json)
          PR_DESCRIPTION=$(jq -r '.description' ../pr.json)
        else
          # Fallback to default values if pr.json doesn't exist
          PR_TITLE="AI Documentation Update"
          PR_DESCRIPTION="Automatically generated documentation update based on source repository changes."
        fi

        BRANCH="codex-doc-update-${GITHUB_RUN_ID}"
        git checkout -b $BRANCH
        git add .
        git commit -m "$PR_TITLE"
        git push origin $BRANCH

        curl -s -X POST \
          -H "Authorization: token ${{ inputs.docs_repo_token }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ inputs.docs_repo }}/pulls \
          -d '{
            "title": "'"$PR_TITLE"'",
            "head": "'"$BRANCH"'",
            "base": "${{ inputs.docs_base_branch }}",
            "body": "'"$PR_DESCRIPTION"'"
          }'
